services:
  mongo:
    restart: always
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./create-schema-product.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - monolith-network
  mongo-express:
    image: mongo-express
    ports:
      - 8092:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_PORT: 27018
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - monolith-network
  monolith-order-product:
    build: ../../monolith
    ports:
      - 8084:8084
    environment:
      MONGO_DB: mongodb://mongo:27017
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 256m
    links:
      - mongo
    networks:
      - monolith-network

networks:
  monolith-network:
    driver: bridge