services:
  mongo:
    restart: always
    image: mongo
    ports:
      - 27016:27017
    volumes:
      - ./create-schema-order.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - microservice-network
#  mongo-express:
#    image: mongo-express
#    ports:
#      - 8090:8081
#    environment:
#      ME_CONFIG_BASICAUTH_USERNAME: user
#      ME_CONFIG_BASICAUTH_PASSWORD: pass
#      ME_CONFIG_MONGODB_PORT: 27016
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root
#    links:
#      - mongo
#    networks:
#      - microservice-network
  microservice-order:
    build: ../../microservice/order
    ports:
      - 8082:8082
    environment:
      MONGO_DB: mongodb://mongo:27017
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 256m
    links:
      - mongo
    networks:
      - microservice-network
  mongo-product:
    restart: always
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./create-schema-product.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - microservice-network
#  mongo-express-product:
#    image: mongo-express
#    ports:
#      - 8091:8081
#    environment:
#      ME_CONFIG_BASICAUTH_USERNAME: user
#      ME_CONFIG_BASICAUTH_PASSWORD: pass
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root
#    links:
#      - mongo
#    networks:
#      - microservice-network
  microservice-product:
    build: ../../microservice/product
    ports:
      - 8083:8083
    environment:
      MONGO_DB: mongodb://mongo-product:27017
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 256m
    links:
      - mongo-product
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge